

GET https://pizza-api.projectcodex.net/api/pizzas



# Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=lasity34

# Get a cart


GET https://pizza-api.projectcodex.net/api/pizza-cart/WfswAWg553/get

# Add a pizza cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json


{
    "cart_code" : "WfswAWg553",
    "pizza_id" : 3
}

#
